# Generated by Django 4.1.7 on 2023-04-03 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_productattribute_options_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartwatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='smartwatch_image/')),
                ('specification', models.TextField()),
                ('model_name', models.CharField(max_length=255)),
                ('screen_size', models.CharField(max_length=255)),
                ('band_material', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.color')),
            ],
            options={
                'verbose_name_plural': '9) Smartwatches',
            },
        ),
    ]
