# Generated by Django 4.1.7 on 2023-04-03 09:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_smartwatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='specification',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
