# Generated by Django 4.1.7 on 2023-04-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_cartorder_cartorderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': 'Items'},
        ),
    ]
