# Generated by Django 4.1.7 on 2023-04-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_alter_cartorder_options_alter_cartorderitems_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitems',
            old_name='image',
            new_name='images',
        ),
    ]
