# Generated by Django 4.1.7 on 2023-04-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_rename_image_cartorderitems_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitems',
            old_name='images',
            new_name='image',
        ),
    ]
