# Generated by Django 4.1.7 on 2023-04-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_alter_cartorder_options_alter_cartorderitems_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
